version: '3.4'

services:
  wikiquizgenerator.api:
    image: ${DOCKER_REGISTRY-}wikiquizgeneratorapi
    build:
      context: .
      dockerfile: src/WikiQuizGenerator.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=WikiQuizGenerator;Username=postgres;Password=YourStrongPassword!
      - ASPNETCORE_URLS=http://+:80