version: "3.8"

services:
  wikiquizgenerator.api:
    image: ${DOCKER_REGISTRY-}wikiquizgeneratorapi
    build:
      context: .
      dockerfile: src/WikiQuizGenerator.Api/Dockerfile
    ports:
      - "5543:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5542:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db-data:
