namespace WikiQuizGenerator.Core.Models;

public class Question
{
    // match names generated by the response
    public string question { get; set; }
    public List<string> options { get; set; }
    public int correctAnswerIndex { get; set; }
}